### ISSUE TITLE
Error code -132 thrown while rebuilding ogg file

### ISSUE THREAD

**Issue by ds5678** [SamboyCoding/Fmod5Sharp#3]
This is a forward from AssetRipper/AssetRipper#285, which got ignored in AssetRipper/AssetRipper#302

Game:
Escape from Tarkov (2019.4.34f1)

AssetRipper log output:
```
ExportedFile : 'transparant_smoke' exported
ExportedFile : 'rainDrop' exported
ExportedFile : 'Water Splash' exported
Import : Resource file 'sharedassets3.assets.resS' has been loaded
ExportedFile : 'dust_splash' exported
ExportedFile : 'raindrop' exported
ExportedFile : 'smoke' exported
[Error] : System.Exception: vorbis_synthesis_headerin threw error code -132
   at Fmod5Sharp.FmodVorbis.FmodVorbisRebuilder.Checked(Int32 result, String name)
   at Fmod5Sharp.FmodVorbis.FmodVorbisRebuilder.RebuildOggFile(FmodSample sample)
   at Fmod5Sharp.FmodSample.RebuildAsStandardFileFormat(Byte[]& data, String& fileExtension)
   at AssetRipper.Library.Exporters.Audio.AudioClipDecoder.TryGetDecodedAudioClipData(Byte[] rawData, Byte[]& decodedData, String& fileExtension) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Audio\AudioClipDecoder.cs:line 70
   at AssetRipper.Library.Exporters.Audio.AudioClipDecoder.TryGetDecodedAudioClipData(IAudioClip audioClip, Byte[]& decodedData, String& fileExtension) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Audio\AudioClipDecoder.cs:line 55
   at AssetRipper.Library.Exporters.Audio.AudioClipExporter.Export(IExportContainer container, IUnityObjectBase asset, String path) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Audio\AudioClipExporter.cs:line 26
   at AssetRipper.Core.Project.Collections.AssetExportCollection.ExportInner(ProjectAssetContainer container, String filePath, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 99
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(ProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 58
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 157
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 68
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 90
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 151
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 132
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 55
```

The error code corresponds to OV_ENOTVORBIS = -132 (https://xiph.org/vorbis/doc/libvorbis/vorbis_synthesis_headerin.html).

**Comment by SamboyCoding** [comment]
This should be fixed in d9aec6fb7e5a07ae1109d50c4c92825064be5c8d
